VirtoCommerce/vc-module-core

VirtoCommerce.Domain/Catalog/Model/PropertyValueType.cs
This pull request goes together with the one I made for the vc-module-catalog repository.
Since the data model already supports Integer as value type for dynamic properties, I propose supporting it in the front-end as well.
=> Add support for  dynamic properties with value type Integer

VirtoCommerce.CoreModule.Web/BackgroundJobs/IndexingJobs.cs
Errors during scale-out indexation are not handled correctly because the tasks are not awaited.
(I'm sorry, my bad)
=> Catch errors during scale-out indexation.

VirtoCommerce.Domain/Pricing/Model/Search/PricesSearchCriteria.cs
Added modified property. Allows for search on prices that were changed since
=> Added Modified to SearchCriteria.

VirtoCommerce.Domain/Cart/Model/Search/ShoppingCartSearchCriteria.cs
VirtoCommerce/vc-module-cart#16
VirtoCommerce/vc-module-cart#15
=> new cart search criteria

.editorconfig, VirtoCommerce.Domain/Marketing/Model/Promotions/Rewards/AmountBasedReward.cs
part of VirtoCommerce/vc-module-marketing#20
=> Limit the reward

VirtoCommerce.Domain/Order/Model/Search/CustomerOrderSearchCriteria.cs
part of https://github.com/VirtoCommerce/vc-module-order/issues/50
=> CustomerOrderSearchCriteria.OrganizationId added

VirtoCommerce.CoreModule.Web/Controllers/Api/StoreFrontSecurityController.cs, VirtoCommerce.CoreModule.Web/Model/SignInCredentials.cs, VirtoCommerce.CoreModule.Web/VirtoCommerce.CoreModule.Web.csproj
Even though the controller is obsolete, we would like to make this more secure. We will look into moving away from this implementation for our project in the following weeks.
=> Get sign in details from body instead of plaintext query

VirtoCommerce.Domain/Order/Model/CustomerOrder.cs
Added a comment to OuterId property.
=> 59 - comment to OuterId property.

VirtoCommerce.CoreModule.Web/Scripts/common/directives/uikit-htmleditor.js
Disabled inline event handlers in UIKit htmleditor
=> #18 The rich text editor 'Codemirror' allows to execute JS code on the page

VirtoCommerce.Domain/Customer/Model/Contact.cs, VirtoCommerce.Domain/Customer/Model/Employee.cs, VirtoCommerce.Domain/Customer/Model/Member.cs, VirtoCommerce.Domain/Customer/Model/Note.cs, VirtoCommerce.Domain/Customer/Model/Organization.cs, VirtoCommerce.Domain/Customer/Model/Vendor.cs
We want to be able to clone Organizations and Contacts. Use case: MemberChangedEvent handlers which update the member. We can't update the newEntity because otherwise other handlers will not get the original newEntity.
Depends on: https://github.com/VirtoCommerce/vc-platform/pull/1524
=> Make contacts and organizations cloneable.

VirtoCommerce.CoreModule.Web/Scripts/common/directives/uikit-htmleditor.js
=> display html editor mode when switch to markdown and back

VirtoCommerce.Domain/Catalog/Model/CatalogProduct.cs, VirtoCommerce.Domain/Catalog/Model/Category.cs
=> dev CategorySearchService does not respect ResponseGroupe

VirtoCommerce.Domain/Store/Model/Search/SearchCriteria.cs
This PR is a part of VirtoCommerce/vc-module-store#22. It adds new fields to store search criteria, so that store service can utilize these fields during store search:
* Store states;
* IDs of fulfillment centers used by store.
=> Search criteria for stores: adding states and fulfillment center IDs.

VirtoCommerce.Domain/Pricing/Model/Price.cs, VirtoCommerce.Domain/Pricing/Model/PriceList.cs, VirtoCommerce.Domain/Pricing/Model/PricelistAssignment.cs, VirtoCommerce.Domain/Pricing/Model/Search/PricelistAssignmentsSearchCriteria.cs, VirtoCommerce.Domain/Pricing/Model/Search/PricelistSearchCriteria.cs, VirtoCommerce.Domain/Pricing/Services/IPricingSearchService.cs
move iClonable changes from v3 to v2 
extend search criteria
=> Move export to v2

NuGet/build.bat, VirtoCommerce.Domain/Catalog/Model/Asset.cs, VirtoCommerce.Domain/Catalog/Model/Catalog.cs, VirtoCommerce.Domain/Catalog/Model/CatalogLanguage.cs, VirtoCommerce.Domain/Catalog/Model/CatalogProduct.cs, VirtoCommerce.Domain/Catalog/Model/Category.cs, VirtoCommerce.Domain/Catalog/Model/CategoryLink.cs, VirtoCommerce.Domain/Catalog/Model/EditorialReview.cs, VirtoCommerce.Domain/Catalog/Model/Image.cs, VirtoCommerce.Domain/Catalog/Model/Outline.cs, VirtoCommerce.Domain/Catalog/Model/OutlineItem.cs, VirtoCommerce.Domain/Catalog/Model/ProductAssociation.cs, VirtoCommerce.Domain/Catalog/Model/Property.cs, VirtoCommerce.Domain/Catalog/Model/PropertyAttribute.cs, VirtoCommerce.Domain/Catalog/Model/PropertyDictionaryItem.cs, VirtoCommerce.Domain/Catalog/Model/PropertyDictionaryItemLocalizedValue.cs, VirtoCommerce.Domain/Catalog/Model/PropertyDictionaryValue.cs, VirtoCommerce.Domain/Catalog/Model/PropertyDisplayName.cs, VirtoCommerce.Domain/Catalog/Model/PropertyValidationRule.cs, VirtoCommerce.Domain/Catalog/Model/PropertyValue.cs, VirtoCommerce.Domain/Catalog/Model/Search/CatalogSearchCriteriaBase.cs, VirtoCommerce.Domain/Catalog/Model/Search/ProductSearchCriteria.cs, VirtoCommerce.Domain/Catalog/Model/Search/PropertyDictionaryItemSearchCriteria.cs, VirtoCommerce.Domain/Catalog/Model/Search/SearchResult.cs, VirtoCommerce.Domain/Commerce/Model/SeoInfo.cs, VirtoCommerce.Domain/Inventory/Model/InventoryInfo.cs
ICloneable implementation for Catalog models;
Extended some SearchCriteria and SearchResults;
=> VP-366: Export support in Catalog module related changes

src/VirtoCommerce.CoreModule.Web/Controllers/Api/CommerceController.cs
=> ProducesResponseType attribute set for NoContent returning actions.

src/VirtoCommerce.CoreModule.Data/Migrations/20000000000000_UpdateCoreV2.cs, src/VirtoCommerce.CoreModule.Data/Migrations/20191218135758_AddSequenceRowVersion.Designer.cs, src/VirtoCommerce.CoreModule.Data/Migrations/20191218135758_AddSequenceRowVersion.cs, src/VirtoCommerce.CoreModule.Data/Model/SequenceEntity.cs, src/VirtoCommerce.CoreModule.Data/Services/SequenceUniqueNumberGeneratorService.cs, src/VirtoCommerce.CoreModule.Data/VirtoCommerce.CoreModule.Data.csproj, tests/VirtoCommerce.CoreModule.Tests/VirtoCommerce.CoreModule.Tests.csproj, tests/VirtoCommerce.Tools.Tests/VirtoCommerce.Tools.Tests.csproj
this changes
https://github.com/VirtoCommerce/vc-module-core/compare/aa4224015558aa7c83615dfe0bc6109f405539bb...9fc747c4c1d7ae59e65918afdda443ff3f4f7d86
Nugets where updated
=> Actualization with changes from v2

VirtoCommerce.Domain/Marketing/Model/Promotions/PromotionEvaluationContext.cs
I have a client that has requested marketing cart promotions related to whether a new order from the storefront is a subscription or not (i.e., has a payment plan). I added the necessary change to this module, and I have more changes ready to send a PR for the changes to vc-module-dynamic-expressions. I'll send those once I hear back on this PR. Let me know if the name `IsRecurring` works or if you have any further suggestions. @tatarincev
=> Add IsRecurring to marketing promo context

VirtoCommerce.CoreModule.Data/Services/CommerceServiceImpl.cs
- Made methods virtual;
- Fixed warnings: ToArray() => AsEnumerable();
- Added comments to Obsolete methods;
- Renamed method parameters to match interface method signature;
=> #144: Make CommerceService methods virtual

VirtoCommerce.Domain/Marketing/Model/Promotions/ProductPromoEntry.cs, VirtoCommerce.Domain/Marketing/Model/Promotions/Rewards/CatalogRecurringItemAmountReward.cs, VirtoCommerce.Domain/VirtoCommerce.Domain.csproj
@tatarincev @yecli I have a follow up PR for the Dynamic Expressions module once this is merged and available.
=> Add recurring support for promotions to line item

VirtoCommerce.Domain/Payment/Model/PaymentStatus.cs
Add Payment statuses, Declined and Error
=> VP-1405 Add Payment statuses, Declined and Error

src/VirtoCommerce.CoreModule.Web/Scripts/common/blades/address-detail.js
VP-1889: Use existing metaFileds
=> VP-1889: First Name and Last name appears on FFC address blade

src/VirtoCommerce.CoreModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VP-3127
=> VP-3127: Set relative iconUrl

.github/workflows/synced-main.yml
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.
=> VP-3187: Initial CI

.github/workflows/synced-main.yml
Sonar Cloud analysis doesn't work
=> VP-3187: Fix sonarcloud analysis

.github/workflows/synced-delivery-dev.yml, .github/workflows/synced-main.yml
Modules need to be deployed to the cargo cd
Build and publish artifact and refer it in vc-deploy-apps
1. Publish artifact to a blob
1. Update link to a module in a "modules.json" (e.g. https://github.com/VirtoCommerce/vc-deploy-apps/blob/master/webstore-app/overlays/dev/modules.json)
N/A
=> VP-3331: Modules deployment implementation

src/VirtoCommerce.CoreModule.Web/Scripts/SEO/widgets/seoWidget.tpl.html
VP-6364 Add icons to widgets inside Product blade
Add icon to the widget
=> VP-6364: Add icons to widgets inside Product blade

src/VirtoCommerce.CoreModule.Web/Scripts/Currency/blades/currency-detail.js, src/VirtoCommerce.CoreModule.Web/Scripts/Currency/blades/currency-list.js, src/VirtoCommerce.CoreModule.Web/Scripts/PackageType/blades/package-type-detail.js, src/VirtoCommerce.CoreModule.Web/Scripts/PackageType/blades/package-type-list.js, src/VirtoCommerce.CoreModule.Web/Scripts/SEO/blades/seo-duplicates.js, src/VirtoCommerce.CoreModule.Web/Scripts/SEO/blades/seo-list.js, src/VirtoCommerce.CoreModule.Web/Scripts/SEO/blades/seo-list.tpl.html, src/VirtoCommerce.CoreModule.Web/Scripts/common/blades/address-detail.js, src/VirtoCommerce.CoreModule.Web/Scripts/common/blades/address-list.js
=> VP-6366: Replace panel action icons

src/VirtoCommerce.CoreModule.Web/Scripts/SEO/blades/seo-detail.js, src/VirtoCommerce.CoreModule.Web/Scripts/SEO/blades/seo-list.js
=> VP-6864: Fix header icon

src/VirtoCommerce.CoreModule.Web/Localizations/en.VirtoCommerce.Core.json, src/VirtoCommerce.CoreModule.Web/Scripts/SEO/blades/seo-detail.tpl.html
https://virtocommerce.atlassian.net/browse/VP-7133
=> VP-7133 add MetaKeywords to SEO info blade

src/VirtoCommerce.CoreModule.Core/Conditions/BlockConditionAndOr.cs
Can boost promotion/rewards calculation by 9-10% because the plain version of IsSatisfiedBy [3x faster](https://github.com/VirtoCommerce/vc-module-marketing/pull/135).
https://virtocommerce.atlassian.net/browse/PT-283
=> PT-346: Performance optimization: LINQless BlockConditionAndOr.IsSatisfiedBy

src/VirtoCommerce.CoreModule.Web/Scripts/Currency/blades/currency-detail.js, src/VirtoCommerce.CoreModule.Web/Scripts/Currency/blades/currency-list.js, src/VirtoCommerce.CoreModule.Web/Scripts/PackageType/blades/package-type-detail.js, src/VirtoCommerce.CoreModule.Web/Scripts/PackageType/blades/package-type-list.js
https://virtocommerce.atlassian.net/browse/PT-669
=> PT-670: Fix money and square icons

src/VirtoCommerce.CoreModule.Core/VirtoCommerce.CoreModule.Core.csproj, src/VirtoCommerce.CoreModule.Data/VirtoCommerce.CoreModule.Data.csproj, src/VirtoCommerce.CoreModule.Web/module.manifest, src/VirtoCommerce.Tools/VirtoCommerce.Tools.csproj
https://virtocommerce.atlassian.net/browse/PT-207
=> PT-207: Enable Source link support

src/VirtoCommerce.CoreModule.Web/Content/css/uikit-htmleditor.css
https://virtocommerce.atlassian.net/browse/PT-625
=> PT-625 Increase icons font size in HTML editor

src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/all-templates.html
Added product code to the selected product in promotion conditions and effects
=> Display product code in promo conditions and effects

src/VirtoCommerce.CoreModule.Web/Scripts/common/blades/address-detail.js, src/VirtoCommerce.CoreModule.Web/Scripts/common/blades/address-detail.tpl.html, src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/all-templates.html, src/VirtoCommerce.CoreModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-1895
address management:
dynamic content management:
=> PT-1895: Display localized country name in UI

src/VirtoCommerce.CoreModule.Web/Localizations/en.VirtoCommerce.Core.json, src/VirtoCommerce.CoreModule.Web/Scripts/common/blades/address-detail.js, src/VirtoCommerce.CoreModule.Web/Scripts/common/blades/address-detail.tpl.html, src/VirtoCommerce.CoreModule.Web/Scripts/common/common.js, src/VirtoCommerce.CoreModule.Web/module.manifest, src/VirtoCommerce.CoreModule.Web/package-lock.json
https://virtocommerce.atlassian.net/browse/PT-1897
=> PT-1899: Change address Region input to selector

src/VirtoCommerce.CoreModule.Web/Scripts/SEO/blades/seo-detail.js, src/VirtoCommerce.CoreModule.Web/Scripts/SEO/blades/seo-detail.tpl.html
=> PT-3549: Add metafrom to seo details blade

.github/workflows/deploy-pr.yml, src/VirtoCommerce.CoreModule.Core/Currency/Currency.cs, src/VirtoCommerce.CoreModule.Core/Currency/DefaultMoneyRoundingPolicy.cs, src/VirtoCommerce.CoreModule.Core/Currency/IMoneyRoundingPolicy.cs, src/VirtoCommerce.CoreModule.Core/Currency/Money.cs, src/VirtoCommerce.CoreModule.Core/Currency/RoundingType.cs, src/VirtoCommerce.CoreModule.Core/Enums/RoundingType.cs, src/VirtoCommerce.CoreModule.Data/Currency/CurrencyEntity.cs, src/VirtoCommerce.CoreModule.Data/Currency/CurrencyService.cs, src/VirtoCommerce.CoreModule.Data/Migrations/20210728124419_roundingpolicy.Designer.cs, src/VirtoCommerce.CoreModule.Data/Migrations/20210728124419_roundingpolicy.cs, src/VirtoCommerce.CoreModule.Web/Localizations/en.VirtoCommerce.Core.json, src/VirtoCommerce.CoreModule.Web/Module.cs, src/VirtoCommerce.CoreModule.Web/Scripts/currency/blades/currency-detail.js, src/VirtoCommerce.CoreModule.Web/Scripts/currency/blades/currency-detail.tpl.html, src/VirtoCommerce.CoreModule.Web/Scripts/virtoCommerce-core.js, tests/VirtoCommerce.CoreModule.Tests/DefaultMoneyRoundingPolicyTests.cs
=> PT-1924: Add rounding policy

docs/How-to override rounding policy.md, src/VirtoCommerce.CoreModule.Core/Currency/DefaultMoneyRoundingPolicy.cs, src/VirtoCommerce.CoreModule.Data/Currency/CurrencyEntity.cs, src/VirtoCommerce.CoreModule.Data/Migrations/20210819064242_ExtendedMidpointRounding.Designer.cs, src/VirtoCommerce.CoreModule.Data/Migrations/20210819064242_ExtendedMidpointRounding.cs, tests/VirtoCommerce.CoreModule.Tests/DefaultMoneyRoundingPolicyTests.cs
=> PT-1924: Fix Rounding policy

src/VirtoCommerce.CoreModule.Core/Common/Address.cs, src/VirtoCommerce.CoreModule.Core/VirtoCommerce.CoreModule.Core.csproj, src/VirtoCommerce.CoreModule.Web/module.manifest, tests/VirtoCommerce.CoreModule.Tests/AddressTest.cs
Extend Address with OuterId property
https://virtocommerce.atlassian.net/browse/PT-4062
=> PT-4060: Extend Address with OuterId property

src/VirtoCommerce.CoreModule.Web/Scripts/common/directives/uikit-htmleditor.js
Show preview in iframe. You can pass an url to a stylesheet to be included in the iframe
=> PT-4584: In IUkit show preview in iframe

src/VirtoCommerce.CoreModule.Web/Scripts/SEO/blades/seo-list.js
=> PT-3807: Fix SEO list delete button

src/VirtoCommerce.CoreModule.Web/Scripts/common/blades/address-detail.js
=> PT-3443: Fix region in Delivery address

src/VirtoCommerce.CoreModule.Web/Localizations/en.VirtoCommerce.Core.json, src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/all-templates.html, src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/dynamicExpression.js
Fixed language errors and improved text and readability in the loc files
https://virtocommerce.atlassian.net/browse/PT-5015
=> docs: Fix language

.github/workflows/main.yml, .github/workflows/publish_nugets.yml, Directory.Build.props, src/VirtoCommerce.CoreModule.Core/VirtoCommerce.CoreModule.Core.csproj, src/VirtoCommerce.CoreModule.Data/Repositories/CoreDbContext.cs, src/VirtoCommerce.CoreModule.Data/VirtoCommerce.CoreModule.Data.csproj, src/VirtoCommerce.CoreModule.Web/VirtoCommerce.CoreModule.Web.csproj, src/VirtoCommerce.CoreModule.Web/module.manifest, src/VirtoCommerce.Tools/VirtoCommerce.Tools.csproj, tests/VirtoCommerce.CoreModule.Tests/VirtoCommerce.CoreModule.Tests.csproj, tests/VirtoCommerce.Tools.Tests/VirtoCommerce.Tools.Tests.csproj
Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956
=>  PT-1956: Bump .Net and EF up to 6

src/VirtoCommerce.CoreModule.Web/Scripts/common/directives/uikit-htmleditor.js
Editor content reset by id
https://virtocommerce.atlassian.net/browse/PT-8007
=> PT-8007: Editor content reset by id

src/VirtoCommerce.CoreModule.Core/Currency/Money.cs
https://virtocommerce.atlassian.net/browse/PT-3999
=> Changing the formattedAmountWithoutCurrency formation logic

src/VirtoCommerce.CoreModule.Core/Common/Address.cs
1) It is necessary to conduct a PR in the coreModule
2) update nuget and migration in CastomerModule
3) update nuget in Xapi and add fields to model
=> Add new field

src/VirtoCommerce.CoreModule.Web/Localizations/de.VirtoCommerce.Core.json, src/VirtoCommerce.CoreModule.Web/Localizations/en.VirtoCommerce.Core.json, src/VirtoCommerce.CoreModule.Web/Localizations/ru.VirtoCommerce.Core.json, src/VirtoCommerce.CoreModule.Web/Scripts/common/common.js
https://virtocommerce.atlassian.net/browse/PT-8487
=> Localizations for address

src/VirtoCommerce.CoreModule.Core/Common/Address.cs, src/VirtoCommerce.CoreModule.Core/Common/EvaluationContextBase.cs, src/VirtoCommerce.CoreModule.Core/Conditions/ConditionJsonConverter.cs, src/VirtoCommerce.CoreModule.Core/Conditions/ConditionTree.cs, src/VirtoCommerce.CoreModule.Core/ModuleConstants.cs, src/VirtoCommerce.CoreModule.Data/Currency/CurrencyEntity.cs, src/VirtoCommerce.CoreModule.Data/ExportImport/CoreExportImport.cs, src/VirtoCommerce.CoreModule.Data/Migrations/20191218135758_AddSequenceRowVersion.cs, src/VirtoCommerce.CoreModule.Data/Migrations/20220929144748_ChangeDecimalsPrecision.Designer.cs, src/VirtoCommerce.CoreModule.Data/Migrations/20220929144748_ChangeDecimalsPrecision.cs, src/VirtoCommerce.CoreModule.Data/Repositories/CoreDbContext.cs, src/VirtoCommerce.CoreModule.Data/Repositories/DesignTimeDbContextFactory.cs, src/VirtoCommerce.CoreModule.Data/Services/SequenceUniqueNumberGeneratorService.cs, src/VirtoCommerce.CoreModule.Web/Controllers/Api/CommerceController.cs, src/VirtoCommerce.CoreModule.Web/Scripts/PackageType/blades/package-type-detail.tpl.html, src/VirtoCommerce.Tools/UrlBuilder.cs, tests/VirtoCommerce.CoreModule.Tests/ConditionUnitTest.cs
Fix scale for decimals
https://virtocommerce.atlassian.net/browse/PT-9204
=> PT-9204: Fix scale for decimals

src/VirtoCommerce.CoreModule.Web/Localizations/ru.VirtoCommerce.Core.json
=> Updated ru localization

src/VirtoCommerce.CoreModule.Core/Common/AddressType.cs
https://virtocommerce.atlassian.net/browse/PT-10238
=> PT-10238: Add Undefined address type

src/VirtoCommerce.CoreModule.Web/Scripts/PackageType/blades/package-type-detail.tpl.html, src/VirtoCommerce.CoreModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-10879
=> remove fraction from package type

src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/expression-directives.js, src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/expression-tree.tpl.html, src/VirtoCommerce.CoreModule.Web/package-lock.json
fix: Broken submenu in options menu
https://virtocommerce.atlassian.net/browse/PT-14058
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Core_3.403.0-pr-219-0016.zip
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Core_3.401.0-pr-219-b813.zip
=> PT-14058: Broken submenu in options menu

.nuke, .nuke/parameters.json, Directory.Build.props, src/VirtoCommerce.CoreModule.Core/VirtoCommerce.CoreModule.Core.csproj, src/VirtoCommerce.CoreModule.Data.MySql/VirtoCommerce.CoreModule.Data.MySql.csproj, src/VirtoCommerce.CoreModule.Data.PostgreSql/VirtoCommerce.CoreModule.Data.PostgreSql.csproj, src/VirtoCommerce.CoreModule.Data.SqlServer/Migrations/20210728124419_roundingpolicy.Designer.cs, src/VirtoCommerce.CoreModule.Data.SqlServer/Migrations/20210728124419_roundingpolicy.cs, src/VirtoCommerce.CoreModule.Data.SqlServer/VirtoCommerce.CoreModule.Data.SqlServer.csproj, src/VirtoCommerce.CoreModule.Data/Repositories/CoreDbContext.cs, src/VirtoCommerce.CoreModule.Data/VirtoCommerce.CoreModule.Data.csproj, src/VirtoCommerce.CoreModule.Web/VirtoCommerce.CoreModule.Web.csproj, src/VirtoCommerce.CoreModule.Web/module.manifest, src/VirtoCommerce.Tools/VirtoCommerce.Tools.csproj, tests/VirtoCommerce.CoreModule.Tests/VirtoCommerce.CoreModule.Tests.csproj, tests/VirtoCommerce.Tools.Tests/VirtoCommerce.Tools.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Core_3.800.0-pr-220-262a.zip
=> PT-14740: .net 8

src/VirtoCommerce.CoreModule.Core/Conditions/UserGroupIsCondition.cs, src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/all-templates.html, src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/dynamicExpression.js
Add a new condition to choose user group in the dynamic expressions in platform
https://virtocommerce.atlassian.net/browse/VCST-272
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Core_3.802.0-pr-222-4715.zip
=> VCST-272: add "UserGroupIs" condition

src/VirtoCommerce.CoreModule.Web/Localizations/en.VirtoCommerce.Core.json, src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/dynamicExpression.js
fix: Rename StateProvince to Region for Address localization.
https://virtocommerce.atlassian.net/browse/VCST-605
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Core_3.805.0-pr-225-a14f.zip
=> VCST-605: Rename StateProvince to Region.

src/VirtoCommerce.CoreModule.Core/Seo/CompositeSeoResolver.cs
fix: Refactored the FindSeoAsync method to resolve fallbackResults if we could not find any result before.
https://virtocommerce.atlassian.net/browse/VCST-1399
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Core_3.817.0-pr-236-b650.zip
=> VCST-1399: Optimize FindSeoAsync method in CompositeSeoResolver

src/VirtoCommerce.CoreModule.Core/Conditions/ConditionTree.cs, src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/all-templates.html, src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/dynamicExpression.js, src/VirtoCommerce.CoreModule.Web/Scripts/dynamicConditions/expression-directives.js, tests/VirtoCommerce.CoreModule.Tests/VirtoCommerce.CoreModule.Tests.csproj, tests/VirtoCommerce.Tools.Tests/VirtoCommerce.Tools.Tests.csproj
https://virtocommerce.atlassian.net/browse/VCST-2470
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Core_3.818.0-pr-237-df77.zip
=> VCST-2470: Move promotion expression templates to the marketing module
